#!/bin/sh
# dmenu-network

gray_1="#222222"
gray_2="#444444"
gray_3="#bbbbbb"
gray_4="#eeeeee"
gray_5="#595959"

font="JetBrainsMono Nerd Font Mono:size=14"

choice=$(nmcli -t -f NAME,TYPE connection show | awk -F: '{print $1 " (" $2 ")"}' | dmenu -i -p "Network:" -fn "$font" -nb "$gray_1" -nf "$gray_3" -sb "$gray_5" -sf "$gray_4")
 
[ -z "$choice" ] && exit

name=$(echo "$choice" | cut -d'(' -f1 | xargs)

nmcli connection up "$name" && notify-send -t 5000 "Connected to $name" || notify-send -t 5000 "Failed"

