#!/bin/sh

options="Lock\nSuspend\nReboot\nShutdown\nLogout"

gray_1="#222222"
gray_2="#444444"
gray_3="#bbbbbb"
gray_4="#eeeeee"
gray_5="#595959"

font="JetBrainsMono Nerd Font Mono:size=14"

chosen=$(echo -e "$options" | dmenu -i -p "Power:" -fn "$font" -nb "$gray_1" -nf "$gray_3" -sb "$gray_5" -sf "$gray_4")

case "$chosen" in
    Lock) slock ;;  # or betterlockscreen, i3lock, etc.
    Suspend) systemctl suspend ;;
    Reboot) systemctl reboot ;;
    Shutdown) systemctl poweroff ;;
    Logout) pkill dwm ;;  # or your logout command
esac

